In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('scores.csv')
df.head().T

             0     1     2     3    4
Status       1     1     2     1    1
Seniority    9    17    10     0    0
Home         1     1     2     1    1
Time        60    60    36    60   36
Age         30    58    46    24   26
Marital      2     3     2     1    1
Records      1     1     2     1    1
Job          3     1     3     1    1
Expenses    73    48    90    63   46
Income     129   131   200   182  107
Assets       0     0  3000  2500    0
Debt         0     0     0     0    0
Amount     800  1000  2000   900  310
Price      846  1658  2985  1325  910

In [3]:
df.shape

(4455, 14)

In [4]:
df.columns = df.columns.str.lower()

In [5]:
df.dtypes

status       int64
seniority    int64
home         int64
time         int64
age          int64
marital      int64
records      int64
job          int64
expenses     int64
income       int64
assets       int64
debt         int64
amount       int64
price        int64
dtype: object

In [6]:
df.status.value_counts()

status
1    3200
2    1254
0       1
Name: count, dtype: int64

In [7]:
status_values = {
    1: 'ok',
    2: 'default',
    0: 'unknown'
}

df.status = df.status.map(status_values)

In [8]:
home_values = {
    1: 'rent',
    2: 'owner',
    3: 'private',
    4: 'ignore',
    5: 'parents',
    6: 'other',
    0: 'unk'
}

df.home = df.home.map(home_values)

In [9]:
marital_values = {
    1: 'single',
    2: 'married',
    3: 'widow',
    4: 'separated',
    5: 'divorced',
    0: 'unk'
}

df.marital = df.marital.map(marital_values)

In [10]:
records_values = {
    1: 'no',
    2: 'yes',
    0: 'unk'
}

df.records = df.records.map(records_values)

In [11]:
job_values = {
    1: 'fixed',
    2: 'partime',
    3: 'freelance',
    4: 'others',
    0: 'unk'
}

df.job = df.job.map(job_values)

In [12]:
df.head()

,status,seniority,home,time,age,marital,records,job,expenses,income,assets,debt,amount,price
0,ok,9,rent,60,30,married,no,freelance,73,129,0,0,800,846
1,ok,17,rent,60,58,widow,no,fixed,48,131,0,0,1000,1658
2,default,10,owner,36,46,married,yes,freelance,90,200,3000,0,2000,2985
3,ok,0,rent,60,24,single,no,fixed,63,182,2500,0,900,1325
4,ok,0,rent,36,26,single,no,fixed,46,107,0,0,310,910

In [13]:
df.dtypes

status         str
seniority    int64
home           str
time         int64
age          int64
marital        str
records        str
job            str
expenses     int64
income       int64
assets       int64
debt         int64
amount       int64
price        int64
dtype: object

In [14]:
df.describe().round(2)

,seniority,time,age,expenses,income,assets,debt,amount,price
count,4455.00,4455.00,4455.00,4455.00,4455.00,4455.00,4455.00,4455.00,4455.00
mean,7.99,46.44,37.08,55.57,763316.99,1060340.81,404381.96,1039.02,1462.88
std,8.17,14.66,10.98,19.52,8703625.26,10217568.67,6344253.40,474.54,628.09
min,0.00,6.00,18.00,35.00,0.00,0.00,0.00,100.00,105.00
25%,2.00,36.00,28.00,35.00,80.00,0.00,0.00,700.00,1117.50
50%,5.00,48.00,36.00,51.00,120.00,3500.00,0.00,1000.00,1400.00
75%,12.00,60.00,45.00,72.00,166.00,6000.00,0.00,1300.00,1692.00
max,48.00,72.00,68.00,180.00,99999999.00,99999999.00,99999999.00,5000.00,11140.00

In [15]:
for col in ['income', 'assets', 'debt']:
    df[col] = df[col].replace(99999999, np.nan)

In [16]:
df.describe().round(2)

,seniority,time,age,expenses,income,assets,debt,amount,price
count,4455.00,4455.00,4455.00,4455.00,4421.00,4408.00,4437.00,4455.00,4455.00
mean,7.99,46.44,37.08,55.57,130.57,5403.43,342.95,1039.02,1462.88
std,8.17,14.66,10.98,19.52,86.37,11573.16,1245.86,474.54,628.09
min,0.00,6.00,18.00,35.00,0.00,0.00,0.00,100.00,105.00
25%,2.00,36.00,28.00,35.00,80.00,0.00,0.00,700.00,1117.50
50%,5.00,48.00,36.00,51.00,120.00,3000.00,0.00,1000.00,1400.00
75%,12.00,60.00,45.00,72.00,165.00,6000.00,0.00,1300.00,1692.00
max,48.00,72.00,68.00,180.00,959.00,300000.00,30000.00,5000.00,11140.00

In [17]:
df = df.drop(df[df.status == 'unknown'].index)

In [18]:
df.shape

(4454, 14)

In [19]:
df.isnull().sum()

status        0
seniority     0
home          0
time          0
age           0
marital       0
records       0
job           0
expenses      0
income       34
assets       47
debt         18
amount        0
price         0
dtype: int64

In [20]:
df = df.fillna(0)

In [21]:
from sklearn.model_selection import train_test_split

train_full_df, test_df = train_test_split(df, test_size=0.2, random_state=1)
train_df, val_df = train_test_split(train_full_df, test_size=0.25, random_state=1)

In [22]:
train_full_df.shape, train_df.shape, val_df.shape, test_df.shape

((3563, 14), (2672, 14), (891, 14), (891, 14))

In [23]:
train_df = train_df.reset_index(drop=True)
val_df = val_df.reset_index(drop=True)
test_df = test_df.reset_index(drop=True)

y_train = (train_df.status == 'ok').astype(int).values
y_val = (val_df.status == 'ok').astype(int).values
y_test = (test_df.status == 'ok').astype(int).values

In [24]:
del train_df['status']
del val_df['status']
del test_df['status']

In [25]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.feature_extraction import DictVectorizer

In [26]:
dv = DictVectorizer(sparse=False)

X_train = dv.fit_transform(train_df.to_dict(orient='records'))
X_val = dv.transform(val_df.to_dict(orient='records'))

In [27]:
model = DecisionTreeClassifier()
model.fit(X_train, y_train)

DecisionTreeClassifier()

In [28]:
y_pred_train = model.predict(X_train)
y_pred_val = model.predict(X_val)

In [29]:
from sklearn.metrics import roc_auc_score

print('train auc-roc score', roc_auc_score(y_train, y_pred_train))
print('validation auc-roc score', roc_auc_score(y_val, y_pred_val))

train auc-roc score 1.0
validation auc-roc score 0.6573548875023634

In [30]:
improved_model = DecisionTreeClassifier(max_depth=2)
improved_model.fit(X_train, y_train)

y_pred_train = improved_model.predict(X_train)
y_pred_val = improved_model.predict(X_val)

print('train auc-roc score', roc_auc_score(y_train, y_pred_train))
print('validation auc-roc score', roc_auc_score(y_val, y_pred_val))

train auc-roc score 0.6156288419945459
validation auc-roc score 0.5965399886557006

In [31]:
stump_model = DecisionTreeClassifier(max_depth=1)
stump_model.fit(X_train, y_train)

y_pred_train = stump_model.predict(X_train)
y_pred_val = stump_model.predict(X_val)

print('train auc-roc score', roc_auc_score(y_train, y_pred_train))
print('validation auc-roc score', roc_auc_score(y_val, y_pred_val))

train auc-roc score 0.5
validation auc-roc score 0.5

In [32]:
from sklearn.tree import export_text

print(export_text(improved_model))

|--- feature_12 <= 89.50
|   |--- feature_27 <= 2.50
|   |   |--- class: 0
|   |--- feature_27 >  2.50
|   |   |--- class: 1
|--- feature_12 >  89.50
|   |--- feature_26 <= 0.50
|   |   |--- class: 1
|   |--- feature_26 >  0.50
|   |   |--- class: 1

In [33]:
data = [
    [8000, 'default'],
    [2000, 'default'],
    [0, 'default'],
    [5000, 'ok'],
    [5000, 'ok'],
    [4000, 'ok'],
    [9000, 'ok'],
    [3000, 'default']
    ]

example_df = pd.DataFrame(data, columns=['assets', 'status'])
example_df

   assets   status
0    8000  default
1    2000  default
2       0  default
3    5000       ok
4    5000       ok
5    4000       ok
6    9000       ok
7    3000  default

In [34]:
example_df.sort_values('status')

   assets   status
0    8000  default
1    2000  default
2       0  default
7    3000  default
3    5000       ok
4    5000       ok
5    4000       ok
6    9000       ok

In [44]:
t = 4000

df_right = example_df[example_df.assets > t]
df_left = example_df[example_df.assets <= t]
print(t)
print('df_left')
print(df_left)
print(df_left.status.value_counts(normalize=True))
print('df_right')
print(df_right)
print(df_right.status.value_counts(normalize=True))
print('--------------')

4000
df_left
   assets   status
1    2000  default
2       0  default
5    4000       ok
7    3000  default
status
default    0.75
ok         0.25
Name: proportion, dtype: float64
df_right
   assets   status
0    8000  default
3    5000       ok
4    5000       ok
6    9000       ok
status
ok         0.75
default    0.25
Name: proportion, dtype: float64
--------------

In [45]:
Ts = [0, 2000, 3000, 4000, 5000, 8000]

for t in Ts:
    df_right = example_df[example_df.assets > t]
    df_left = example_df[example_df.assets <= t]
    print(t)
    print('df_left')
    print(df_left)
    print(df_left.status.value_counts(normalize=True))
    print('df_right')
    print(df_right)
    print(df_right.status.value_counts(normalize=True))
    print('--------------')

0
df_left
   assets   status
2       0  default
status
default    1.0
Name: proportion, dtype: float64
df_right
   assets   status
0    8000  default
1    2000  default
3    5000       ok
4    5000       ok
5    4000       ok
6    9000       ok
7    3000  default
status
ok         0.571429
default    0.428571
Name: proportion, dtype: float64
--------------
2000
df_left
   assets   status
1    2000  default
2       0  default
status
default    1.0
Name: proportion, dtype: float64
df_right
   assets   status
0    8000  default
3    5000       ok
4    5000       ok
5    4000       ok
6    9000       ok
7    3000  default
status
ok         0.666667
default    0.333333
Name: proportion, dtype: float64
--------------
3000
df_left
   assets   status
1    2000  default
2       0  default
7    3000  default
status
default    1.0
Name: proportion, dtype: float64
df_right
   assets   status
0    8000  default
3    5000       ok
4    5000       ok
5    4000       ok
6    9000       ok
status
ok         0.8
default    0.2
Name: proportion, dtype: float64
--------------
4000
df_left
   assets   status
1    2000  default
2       0  default
5    4000       ok
7    3000  default
status
default    0.75
ok         0.25
Name: proportion, dtype: float64
df_right
   assets   status
0    8000  default
3    5000       ok
4    5000       ok
6    9000       ok
status
ok         0.75
default    0.25
Name: proportion, dtype: float64
--------------
5000
df_left
   assets   status
1    2000  default
2       0  default
3    5000       ok
4    5000       ok
5    4000       ok
7    3000  default
status
default    0.5
ok         0.5
Name: proportion, dtype: float64
df_right
   assets   status
0    8000  default
6    9000       ok
status
default    0.5
ok         0.5
Name: proportion, dtype: float64
--------------
8000
df_left
   assets   status
0    8000  default
1    2000  default
2       0  default
3    5000       ok
4    5000       ok
5    4000       ok
7    3000  default
status
default    0.571429
ok         0.428571
Name: proportion, dtype: float64
df_right
   assets status
6    9000     ok
status
ok    1.0
Name: proportion, dtype: float64
--------------